apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sparkclusters.radanalytics.io
spec:
  conversion:
    strategy: None
  group: radanalytics.io
  names:
    kind: SparkCluster
    listKind: SparkClusterList
    plural: sparkclusters
    singular: sparkcluster
  # preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
     openAPIV3Schema:
      description: >-
        Defining the CRD so to use the as-is jhhub from ODH
      type: object
      properties:
        spec:
          type: object
          x-kubernetes-preserve-unknown-fields: true

# kind: CustomResourceDefinition
# apiVersion: apiextensions.k8s.io/v1beta1
# metadata:
#   name: sparkclusters.radanalytics.io
# spec:
#   group: radanalytics.io
#   names:
#     kind: SparkCluster
#     listKind: SparkClusterList
#     plural: sparkclusters
#     singular: sparkcluster
#   scope: Namespaced
#   version: v1
#   additionalPrinterColumns:
#   - name: Workers
#     type: string
#     description: The number of workers in the Spark cluster
#     JSONPath: .spec.worker.instances
#   - name: Age
#     type: date
#     JSONPath: .metadata.creationTimestamp
#   subresources:
#     status: {}
